begin;
drop function if exists barbershop_has_access(uuid);
drop table if exists notification_logs;
drop table if exists ai_conversation_history;
drop table if exists whatsapp_messages;
drop table if exists whatsapp_conversations;
drop table if exists ai_settings;
drop table if exists waiting_list;
drop table if exists holidays;
drop table if exists schedule_breaks;
drop table if exists customer_consents;
drop table if exists barbershop_units;
alter table subscriptions drop column if exists notes;
alter table subscriptions drop column if exists payment_method;
alter table subscriptions drop column if exists next_billing_at;
alter table subscriptions drop column if exists last_renewed_at;
alter table subscriptions drop column if exists grace_days;
alter table subscriptions drop column if exists trial_until;
alter table subscriptions drop column if exists billing_day;
alter table subscriptions drop column if exists monthly_value;
alter table plans drop column if exists max_units;
alter table plans drop column if exists max_barbers;
alter table plans drop column if exists monthly_price;
commit;
