begin;
create extension if not exists pgcrypto;
create extension if not exists btree_gist;
create type barbershop_status as enum ('trial','active','past_due','suspended','cancelled');
create type appointment_status as enum ('scheduled','confirmed','arrived','in_service','completed','cancelled','no_show','rescheduled');
create type message_status as enum ('pending','processing','retry','sent','skipped','cancelled','dead');

create table plans(id uuid primary key default gen_random_uuid(),name text unique not null,price numeric(12,2) not null default 0,limits jsonb not null default '{}',features jsonb not null default '{}',active boolean not null default true);
create table barbershops(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null check(slug~'^[a-z0-9]+(?:-[a-z0-9]+)*$'),timezone text not null default 'America/Fortaleza',status barbershop_status not null default 'trial',settings jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table subscriptions(id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references barbershops on delete restrict,plan_id uuid not null references plans,starts_at timestamptz not null,expires_at timestamptz not null,grace_until timestamptz,status text not null,created_at timestamptz not null default now());
create table profiles(id uuid primary key references auth.users on delete cascade,barbershop_id uuid references barbershops on delete restrict,role text not null check(role in('superadmin','owner','manager','receptionist','barber')),display_name text not null,status text not null default 'active',created_at timestamptz not null default now(),check((role='superadmin' and barbershop_id is null) or (role<>'superadmin' and barbershop_id is not null)));
create table audit_logs(id bigint generated always as identity primary key,barbershop_id uuid references barbershops,actor_id uuid,action text not null,entity text not null,entity_id uuid,metadata jsonb not null default '{}',ip inet,created_at timestamptz not null default now());

create table services(id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references barbershops on delete restrict,name text not null,duration_minutes int not null check(duration_minutes between 1 and 480),buffer_minutes int not null default 0 check(buffer_minutes between 0 and 120),price numeric(12,2) not null default 0,return_days int not null default 28 check(return_days between 1 and 365),active boolean not null default true,public boolean not null default true,unique(barbershop_id,name));
create table barbers(id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references barbershops on delete restrict,user_id uuid references profiles,display_name text not null,active boolean not null default true,public boolean not null default true,unique(barbershop_id,id));
create table barber_services(barbershop_id uuid not null references barbershops,barber_id uuid not null,service_id uuid not null,primary key(barbershop_id,barber_id,service_id),foreign key(barbershop_id,barber_id) references barbers(barbershop_id,id),foreign key(service_id) references services(id));
create table working_hours(id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references barbershops,barber_id uuid references barbers,weekday int not null check(weekday between 0 and 6),start_time time not null,end_time time not null,check(start_time<end_time));
create table schedule_blocks(id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references barbershops,barber_id uuid references barbers,starts_at timestamptz not null,ends_at timestamptz not null,reason text,check(starts_at<ends_at));
create table customers(id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references barbershops,name text not null,phone_e164 text not null check(phone_e164~'^\+[1-9][0-9]{7,14}$'),consent_at timestamptz,do_not_contact boolean not null default false,notes text,unique(barbershop_id,phone_e164));
create table appointments(id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references barbershops,customer_id uuid not null references customers,barber_id uuid not null references barbers,service_id uuid not null references services,starts_at timestamptz not null,ends_at timestamptz not null,status appointment_status not null default 'scheduled',source text not null default 'public',management_token_hash text,completed_at timestamptz,completed_by uuid references profiles,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(starts_at<ends_at));
alter table appointments add constraint no_active_overlap exclude using gist(barber_id with =,tstzrange(starts_at,ends_at,'[)') with &&) where(status in('scheduled','confirmed','arrived','in_service'));
create index appointments_tenant_start_idx on appointments(barbershop_id,starts_at);
create table appointment_status_history(id bigint generated always as identity primary key,barbershop_id uuid not null references barbershops,appointment_id uuid not null references appointments,from_status appointment_status,to_status appointment_status not null,actor_id uuid,created_at timestamptz not null default now());
create table whatsapp_connections(id uuid primary key default gen_random_uuid(),barbershop_id uuid not null unique references barbershops,instance_key text not null unique,status text not null default 'offline',encrypted_credentials bytea,last_seen_at timestamptz);
create table automation_rules(id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references barbershops,service_id uuid references services,type text not null,delay_days int,send_time time not null default '14:00',template text not null,active boolean not null default true,unique(barbershop_id,service_id,type));
create table scheduled_messages(id uuid primary key default gen_random_uuid(),barbershop_id uuid not null references barbershops,customer_id uuid not null references customers,appointment_id uuid references appointments,type text not null,body text not null,send_at timestamptz not null,status message_status not null default 'pending',attempts int not null default 0,next_retry_at timestamptz,locked_at timestamptz,sent_at timestamptz,last_error text,provider_id text,idempotency_key text not null unique,created_at timestamptz not null default now());
create index scheduled_messages_due_idx on scheduled_messages(status,send_at);
create table webhook_events(id bigint generated always as identity primary key,barbershop_id uuid not null references barbershops,provider text not null,event_id text not null,payload jsonb not null,created_at timestamptz not null default now(),unique(provider,event_id));
commit;
