import {FormEvent,useEffect,useState} from "react";
import {Link,Navigate,Route,Routes,useNavigate,useParams} from "react-router-dom";
import type {Session} from "@supabase/supabase-js";
import {api,supabase} from "./api";

type Item={id:string;name:string;duration_minutes:number;price:number};
type WhatsAppState={status:"offline"|"connecting"|"connected";phone_number:string|null;last_seen_at:string|null};
type ConnectResult={status:string;qrcode:string|null;pairing_code:string|null};
const roleOf=(session:Session|null)=>String(session?.user.app_metadata?.role||"");
function Shell({kind,children}:{kind:string;children:React.ReactNode}){const navigate=useNavigate();const logout=async()=>{await supabase.auth.signOut();navigate("/login",{replace:true})};return <div className="shell"><aside><b>BF BarberFlow</b><small>{kind}</small><nav><Link to="/app">Dashboard</Link><Link to="/app/agenda">Agenda</Link><Link to="/app/services">Serviços</Link><Link to="/app/whatsapp">WhatsApp</Link><button className="logout" onClick={logout}>Sair</button></nav></aside><main>{children}</main></div>}
function Login(){const[e,setE]=useState("");const[p,setP]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const navigate=useNavigate();useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session)navigate(roleOf(data.session)==="superadmin"?"/admin":"/app",{replace:true})})},[navigate]);const submit=async(x:FormEvent)=>{x.preventDefault();setBusy(true);setError("");const{data,error:authError}=await supabase.auth.signInWithPassword({email:e.trim(),password:p});setBusy(false);if(authError||!data.session){setError(authError?.message==="Invalid login credentials"?"E-mail ou senha incorretos.":authError?.message||"Não foi possível entrar.");return}navigate(roleOf(data.session)==="superadmin"?"/admin":"/app",{replace:true})};return <div className="login"><form onSubmit={submit}><h1>BarberFlow</h1><p>Acesso seguro</p><input aria-label="E-mail" type="email" autoComplete="username" required value={e} onChange={x=>setE(x.target.value)}/><input aria-label="Senha" type="password" autoComplete="current-password" required value={p} onChange={x=>setP(x.target.value)}/>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy}>{busy?"Entrando...":"Entrar"}</button></form></div>}
function Protected({admin=false,children}:{admin?:boolean;children:React.ReactNode}){const[session,setSession]=useState<Session|null|undefined>(undefined);useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>data.subscription.unsubscribe()},[]);if(session===undefined)return <div className="loading">Carregando...</div>;if(!session)return <Navigate to="/login" replace/>;if(admin&&roleOf(session)!=="superadmin")return <Navigate to="/app" replace/>;if(!admin&&roleOf(session)==="superadmin")return <Navigate to="/admin" replace/>;return <>{children}</>}
function Dashboard(){return <Shell kind="BARBEARIA"><header><h1>Visão operacional</h1></header><section className="cards">{[["Agendamentos hoje","12"],["Ocupação","78%"],["Faturamento","R$ 640"],["Retornos programados","24"]].map(x=><article key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong></article>)}</section><article className="panel"><h2>Próximos atendimentos</h2><p>09:00 · Lucas · Corte degradê</p><p>10:15 · Rafael · Barba completa</p><p>11:00 · Bruno · Corte + barba</p></article></Shell>}
function Services(){const[items,setItems]=useState<Item[]>([]);useEffect(()=>{api<Item[]>("/api/app/services").then(setItems).catch(()=>{})},[]);return <Shell kind="BARBEARIA"><h1>Serviços</h1><article className="panel">{items.length?items.map(x=><p key={x.id}><b>{x.name}</b> · {x.duration_minutes} min · R$ {x.price}</p>):<p>Conecte a API para carregar os serviços da barbearia.</p>}</article></Shell>}
function WhatsApp(){
 const[state,setState]=useState<WhatsAppState>({status:"offline",phone_number:null,last_seen_at:null});
 const[qr,setQr]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 const load=()=>api<WhatsAppState>("/api/app/whatsapp").then(value=>{setState(value);if(value.status==="connected")setQr(null)}).catch(e=>setError(e.message));
 useEffect(()=>{load();const timer=window.setInterval(load,5000);return()=>window.clearInterval(timer)},[]);
 const connect=async()=>{setBusy(true);setError("");try{const result=await api<ConnectResult>("/api/app/whatsapp/connect",{method:"POST"});setQr(result.qrcode);setState(s=>({...s,status:"connecting"}));if(!result.qrcode)setError("Aguardando o QR Code. Clique novamente em alguns segundos.")}catch(e){setError(e instanceof Error?e.message:"Não foi possível conectar")}finally{setBusy(false)}};
 const disconnect=async()=>{if(!confirm("Desconectar o WhatsApp desta barbearia?"))return;setBusy(true);setError("");try{await api<void>("/api/app/whatsapp",{method:"DELETE"});setQr(null);setState({status:"offline",phone_number:null,last_seen_at:null})}catch(e){setError(e instanceof Error?e.message:"Não foi possível desconectar")}finally{setBusy(false)}};
 const label=state.status==="connected"?"Conectado":state.status==="connecting"?"Aguardando leitura do QR Code":"Não conectado";
 return <Shell kind="BARBEARIA"><h1>WhatsApp da barbearia</h1><article className="panel whatsapp-panel"><div className={`status ${state.status}`}><span/> {label}</div>{state.phone_number&&<p><b>Número conectado:</b> {state.phone_number}</p>}<p>Este único número enviará lembretes de horários e mensagens de retorno para os clientes desta barbearia.</p>{qr&&<div className="qr"><h2>Escaneie o QR Code</h2><img src={qr} alt="QR Code para conectar o WhatsApp"/><ol><li>Abra o WhatsApp no celular.</li><li>Entre em <b>Aparelhos conectados</b>.</li><li>Toque em <b>Conectar aparelho</b> e escaneie.</li></ol></div>}{error&&<p className="error" role="alert">{error}</p>}<div className="actions">{state.status!=="connected"&&<button onClick={connect} disabled={busy}>{busy?"Aguarde...":qr?"Gerar novo QR Code":"Conectar WhatsApp"}</button>}{state.status==="connected"&&<button className="danger" onClick={disconnect} disabled={busy}>Desconectar WhatsApp</button>}</div></article></Shell>
}
function Booking(){const{slug}=useParams();const[services,setServices]=useState<Item[]>([]);const[selected,setSelected]=useState("");const[message,setMessage]=useState("");useEffect(()=>{api<Item[]>(`/api/public/${slug}/services`).then(setServices)},[slug]);const book=async()=>{await api(`/api/public/${slug}/appointments`,{method:"POST",body:JSON.stringify({service_id:selected,barber_id:null,starts_at:new Date(Date.now()+86400000).toISOString(),customer_name:"Cliente",customer_phone:"+5585999999999"})});setMessage("Agendamento confirmado")};return <div className="public"><h1>Agende seu horário</h1><p>Escolha um serviço. A disponibilidade é revalidada no servidor.</p>{services.map(s=><button key={s.id} className={selected===s.id?"selected":""} onClick={()=>setSelected(s.id)}>{s.name}<span>{s.duration_minutes} min · R$ {s.price}</span></button>)}<button disabled={!selected} onClick={book}>Confirmar</button><b>{message}</b></div>}
function Admin(){return <Shell kind="SUPERADMIN"><h1>Empresas e assinaturas</h1><section className="cards"><article><small>Ativas</small><strong>42</strong></article><article><small>Vencendo</small><strong>6</strong></article><article><small>Suspensas</small><strong>2</strong></article></section><article className="panel">Criação de empresa, proprietário, plano, validade, suspensão e reativação disponíveis pela API administrativa.</article></Shell>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/admin/*" element={<Protected admin><Admin/></Protected>}/><Route path="/app" element={<Protected><Dashboard/></Protected>}/><Route path="/app/services" element={<Protected><Services/></Protected>}/><Route path="/app/whatsapp" element={<Protected><WhatsApp/></Protected>}/><Route path="/app/*" element={<Protected><Dashboard/></Protected>}/><Route path="/agendar/:slug" element={<Booking/>}/><Route path="*" element={<Navigate to="/login" replace/>}/></Routes>}
