import{FormEvent,useEffect,useState}from"react";import{Link,Navigate,Route,Routes,useParams}from"react-router-dom";import{api,supabase}from"./api";
type Item={id:string;name:string;duration_minutes:number;price:number};
const Shell=({kind,children}:{kind:string,children:React.ReactNode})=><div className="shell"><aside><b>BF BarberFlow</b><small>{kind}</small><nav><Link to="/app">Dashboard</Link><Link to="/app/agenda">Agenda</Link><Link to="/app/services">Serviços</Link><Link to="/app/whatsapp">WhatsApp</Link></nav></aside><main>{children}</main></div>;
function Login(){const[e,setE]=useState("");const[p,setP]=useState("");const submit=async(x:FormEvent)=>{x.preventDefault();await supabase.auth.signInWithPassword({email:e,password:p});location.href="./app"};return <div className="login"><form onSubmit={submit}><h1>BarberFlow</h1><p>Acesso seguro da barbearia</p><input aria-label="E-mail" value={e} onChange={x=>setE(x.target.value)}/><input aria-label="Senha" type="password" value={p} onChange={x=>setP(x.target.value)}/><button>Entrar</button></form></div>}
function Dashboard(){return <Shell kind="BARBEARIA"><header><h1>Visão operacional</h1></header><section className="cards">{[["Agendamentos hoje","12"],["Ocupação","78%"],["Faturamento","R$ 640"],["Retornos programados","24"]].map(x=><article><small>{x[0]}</small><strong>{x[1]}</strong></article>)}</section><article className="panel"><h2>Próximos atendimentos</h2><p>09:00 · Lucas · Corte degradê</p><p>10:15 · Rafael · Barba completa</p><p>11:00 · Bruno · Corte + barba</p></article></Shell>}
function Services(){const[items,setItems]=useState<Item[]>([]);useEffect(()=>{api<Item[]>("/api/app/services").then(setItems).catch(()=>{})},[]);return <Shell kind="BARBEARIA"><h1>Serviços</h1><article className="panel">{items.length?items.map(x=><p key={x.id}><b>{x.name}</b> · {x.duration_minutes} min · R$ {x.price}</p>):<p>Conecte a API para carregar os serviços do tenant autenticado.</p>}</article></Shell>}
function Booking(){const{slug}=useParams();const[services,setServices]=useState<Item[]>([]);const[selected,setSelected]=useState("");const[message,setMessage]=useState("");useEffect(()=>{api<Item[]>(`/api/public/${slug}/services`).then(setServices)},[slug]);const book=async()=>{await api(`/api/public/${slug}/appointments`,{method:"POST",body:JSON.stringify({service_id:selected,barber_id:null,starts_at:new Date(Date.now()+86400000).toISOString(),customer_name:"Cliente",customer_phone:"+5585999999999"})});setMessage("Agendamento confirmado")};return <div className="public"><h1>Agende seu horário</h1><p>Escolha um serviço. A disponibilidade é revalidada no servidor.</p>{services.map(s=><button className={selected===s.id?"selected":""} onClick={()=>setSelected(s.id)}>{s.name}<span>{s.duration_minutes} min · R$ {s.price}</span></button>)}<button disabled={!selected} onClick={book}>Confirmar</button><b>{message}</b></div>}
function Admin(){return <Shell kind="SUPERADMIN"><h1>Empresas e assinaturas</h1><section className="cards"><article><small>Ativas</small><strong>42</strong></article><article><small>Vencendo</small><strong>6</strong></article><article><small>Suspensas</small><strong>2</strong></article></section><article className="panel">Criação de empresa, proprietário, plano, validade, suspensão e reativação disponíveis pela API administrativa.</article></Shell>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/admin/*" element={<Admin/>}/><Route path="/app" element={<Dashboard/>}/><Route path="/app/services" element={<Services/>}/><Route path="/app/*" element={<Dashboard/>}/><Route path="/agendar/:slug" element={<Booking/>}/><Route path="*" element={<Navigate to="/login"/>}/></Routes>}
